[alembic]
script_location = alembic
sqlalchemy.url = postgresql://user:pass@localhost/dbname
prepend_sys_path = .

[logger_root]
level = WARNING
handlers = console

[handler_console]
class = StreamHandler
args = (sys.stderr,)
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S